version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  functions:
    build:
      context: .
      dockerfile: docker/functions/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./functions:/functions
      - /functions/node_modules
